#pragma once

//from GOOE3.h

#define GOOE_MOUSE_BUTTON_1         0
#define GOOE_MOUSE_BUTTON_2         1
#define GOOE_MOUSE_BUTTON_3         2
#define GOOE_MOUSE_BUTTON_4         3
#define GOOE_MOUSE_BUTTON_5         4
#define GOOE_MOUSE_BUTTON_6         5
#define GOOE_MOUSE_BUTTON_7         6
#define GOOE_MOUSE_BUTTON_8         7
#define GOOE_MOUSE_BUTTON_LAST      GOOE_MOUSE_BUTTON_8
#define GOOE_MOUSE_BUTTON_LEFT      GOOE_MOUSE_BUTTON_1
#define GOOE_MOUSE_BUTTON_RIGHT     GOOE_MOUSE_BUTTON_2
#define GOOE_MOUSE_BUTTON_MIDDLE    GOOE_MOUSE_BUTTON_3
